
bakery=Bakery('New')
print(bakery.add_drink('Tea', 'Fuse', 200, 'Ahmad'))
print(bakery.add_drink('Water', 'Devin', 200, 'Water'))
print(bakery.drinks_menu)
print(bakery.add_food('Bread', 'New', 2.50))
print(bakery.add_food('Cake', 'Old', 1.50))
print(bakery.food_menu)
print(bakery.add_table('Inside', 1, 10))
print(bakery.add_table('Inside', 2, 10))
print(bakery.add_table('Inside', 3, 10))
print(bakery.reserve_table(10))
print(bakery.reserve_table(10))
print(bakery.order_food(2, 'New', 'Old', 'Milk', "Cheese"))
print(bakery.order_drink(2, 'Fuse', 'Devin', 'not', "now"))
print(bakery.leave_table(2))
print(bakery.get_free_tables_info())
print(bakery.get_total_income())
